### ISSUE TITLE
vm: * The 'ansible_local' provisioner could not be found. Error

### ISSUE THREAD

**Issue by SenthilRoyann** [William-Yeh/docker-workshop#11]
I am getting

vm:
- The 'ansible_local' provisioner could not be found.

What is the solution...?

**Comment by William-Yeh** [comment]
Hi,

Where did you encounter this error?

**Comment by SenthilRoyann** [comment]
Hi william, thanks for replying...
I reinstalled 'Vagrant' its working fine
