### ISSUE TITLE
vagrant failed to bring up machine

### ISSUE THREAD

**Issue by yangacer** [William-Yeh/docker-workshop#5]
Versions:
- Vagrant 1.7.2
- VBoxManage 4.3.20r96996

Error:

```
==> main: Successfully added box 'williamyeh/ubuntu-trusty64-docker' (v1.5.0.2) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The '' provisioner could not be found.
```

vagrant status

```
vagrant status
Current machine states:

main                      not created (virtualbox)
alice                     not created (virtualbox)
bob                       not created (virtualbox)
centos                    poweroff (virtualbox)
registry                  not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

**Comment by William-Yeh** [comment]
Have you executed the following 2 commands before `setup-vagrant`, as mentioned in `https://github.com/William-Yeh/docker-workshop/blob/master/config.md`?

```
vagrant plugin install vagrant-hosts
vagrant plugin install vagrant-vbox-snapshot
```

**Comment by yangacer** [comment]
Oops. I install plugins with `sudo` and run script with non root privilege. Is there a way to avoid download all boxes again?

**Comment by William-Yeh** [comment]
`vagrant up --no-provision` to avoid running provisioning procedures again.

**Comment by yangacer** [comment]
Awesome! And nice tutorial!

**Comment by William-Yeh** [comment]
[Memo] The issue would disappear since Version 3.  To simply setup procedure, Vagrant plugins `vagrant-hosts` and `vagrant-vbox-snapshot` are not required anymore.
