### ISSUE TITLE
請問main box 無法安裝?

### ISSUE THREAD

**Issue by williamhuang1982** [William-Yeh/docker-workshop#9]
Bringing machine 'main' up with 'virtualbox' provider...
==> main: Box 'williamyeh/ubuntu-trusty64-docker' could not be found. Attempting
 to find and install...
    main: Box Provider: virtualbox
    main: Box Version: >= 1.5.0
==> main: Loading metadata for box 'williamyeh/ubuntu-trusty64-docker'
    main: URL: https://atlas.hashicorp.com/williamyeh/ubuntu-trusty64-docker
Waiting for cleanup before exiting...

**Comment by William-Yeh** [comment]
Sometimes the atlas.hashicorp.com server has some downtime. Keep trying several minutes later.
